"""Structured configuration package for client scripts and utils.

Backwards compatible: re-exports commonly used constants for existing imports.
"""

from __future__ import annotations

# Environment
from .env import ENV_VOXTRAL_API_KEY

# Files / samples
from .samples import FILE_EXTS, SAMPLES_DIR_NAME

# Idle
from .idle import IDLE_GRACE_PERIOD_S, SERVER_IDLE_TIMEOUT_S

# Defaults
from .defaults import MS_PER_S, DEFAULT_ZERO, DEFAULT_TIMEOUT_S

# STT timing
from .stt import STT_DELAY_SEC, SERVER_STEP_MS, SERVER_STEP_SEC

# Session and handshake
from .session import MIN_SLEEP_S, POLL_INTERVAL_S, DONE_WAIT_TIMEOUT_S, READY_WAIT_TIMEOUT_S

# Audio-related
from .audio import CHUNK_MS, CHUNK_SAMPLES, FRAME_TIME_SEC, ASR_SAMPLE_RATE, PCM16_MAX_VALUE, FFMPEG_DECODE_SR_16K

# WebSocket settings
from .websocket import (
    WS_ENDPOINT_PATH,
    WS_PING_TIMEOUT_S,
    WS_PING_INTERVAL_S,
    WS_CLOSE_CODE_NORMAL,
    WS_MAX_MESSAGE_BYTES,
    WS_CLOSE_REASON_CLIENT_DONE,
)

# Timeouts and allowances
from .timeouts import (
    JITTER_STEP_S,
    JITTER_GROUP_SIZE,
    COMPUTE_TIMEOUT_MAX_S,
    COMPUTE_TIMEOUT_MIN_S,
    FINALIZE_ALLOWANCE_CAP_S,
    FINALIZE_ALLOWANCE_EXTRA_S,
    HANDSHAKE_ALLOWANCE_WAIT_S,
    COMPUTE_TIMEOUT_SAFETY_MULT,
    COMPUTE_TIMEOUT_SAFETY_ADD_S,
    HANDSHAKE_ALLOWANCE_NO_WAIT_S,
)

# Protocol
from .protocol import (
    PROTO_KEY_TYPE,
    PROTO_TYPE_END,
    PROTO_TYPE_PING,
    PROTO_TYPE_PONG,
    PROTO_TYPE_ERROR,
    PROTO_KEY_PAYLOAD,
    PROTO_TYPE_CANCEL,
    PROTO_KEY_REQUEST_ID,
    PROTO_KEY_SESSION_ID,
    PROTO_TYPE_AUDIO_APPEND,
    PROTO_TYPE_AUDIO_COMMIT,
    PROTO_TYPE_SESSION_UPDATE,
    PROTO_TYPE_SESSION_CREATED,
    PROTO_TYPE_SESSION_UPDATED,
    PROTO_TYPE_TRANSCRIPTION_DONE,
    PROTO_TYPE_TRANSCRIPTION_DELTA,
)

__all__ = [
    "ASR_SAMPLE_RATE",
    "COMPUTE_TIMEOUT_MAX_S",
    "COMPUTE_TIMEOUT_MIN_S",
    "COMPUTE_TIMEOUT_SAFETY_ADD_S",
    "COMPUTE_TIMEOUT_SAFETY_MULT",
    "DEFAULT_TIMEOUT_S",
    "DEFAULT_ZERO",
    "DONE_WAIT_TIMEOUT_S",
    "ENV_VOXTRAL_API_KEY",
    "FFMPEG_DECODE_SR_16K",
    "FILE_EXTS",
    "FINALIZE_ALLOWANCE_CAP_S",
    "FINALIZE_ALLOWANCE_EXTRA_S",
    "FRAME_TIME_SEC",
    "HANDSHAKE_ALLOWANCE_NO_WAIT_S",
    "HANDSHAKE_ALLOWANCE_WAIT_S",
    "IDLE_GRACE_PERIOD_S",
    "JITTER_GROUP_SIZE",
    "JITTER_STEP_S",
    "MIN_SLEEP_S",
    "MS_PER_S",
    "PCM16_MAX_VALUE",
    "POLL_INTERVAL_S",
    "PROTO_KEY_PAYLOAD",
    "PROTO_KEY_REQUEST_ID",
    "PROTO_KEY_SESSION_ID",
    "PROTO_KEY_TYPE",
    "PROTO_TYPE_AUDIO_APPEND",
    "PROTO_TYPE_AUDIO_COMMIT",
    "PROTO_TYPE_CANCEL",
    "PROTO_TYPE_END",
    "PROTO_TYPE_ERROR",
    "PROTO_TYPE_PING",
    "PROTO_TYPE_PONG",
    "PROTO_TYPE_SESSION_CREATED",
    "PROTO_TYPE_SESSION_UPDATE",
    "PROTO_TYPE_SESSION_UPDATED",
    "PROTO_TYPE_TRANSCRIPTION_DELTA",
    "PROTO_TYPE_TRANSCRIPTION_DONE",
    "READY_WAIT_TIMEOUT_S",
    "SAMPLES_DIR_NAME",
    "SERVER_IDLE_TIMEOUT_S",
    "SERVER_STEP_MS",
    "SERVER_STEP_SEC",
    "STT_DELAY_SEC",
    "WS_CLOSE_CODE_NORMAL",
    "WS_CLOSE_REASON_CLIENT_DONE",
    "WS_ENDPOINT_PATH",
    "WS_MAX_MESSAGE_BYTES",
    "WS_PING_INTERVAL_S",
    "WS_PING_TIMEOUT_S",
    "CHUNK_MS",
    "CHUNK_SAMPLES",
]
