"""Configuration module exports (constants only)."""

from .limits import (
    ENV_WS_CANCEL_WINDOW_SECONDS,
    ENV_WS_MAX_CANCELS_PER_WINDOW,
    ENV_WS_MESSAGE_WINDOW_SECONDS,
    ENV_MAX_CONCURRENT_CONNECTIONS,
    ENV_WS_MAX_MESSAGES_PER_WINDOW,
    DEFAULT_WS_CANCEL_WINDOW_SECONDS,
    DEFAULT_WS_MAX_CANCELS_PER_WINDOW,
    DEFAULT_WS_MESSAGE_WINDOW_SECONDS,
    DEFAULT_MAX_CONCURRENT_CONNECTIONS,
    DEFAULT_WS_MAX_MESSAGES_PER_WINDOW,
)

__all__ = [
    "DEFAULT_MAX_CONCURRENT_CONNECTIONS",
    "DEFAULT_WS_CANCEL_WINDOW_SECONDS",
    "DEFAULT_WS_MAX_CANCELS_PER_WINDOW",
    "DEFAULT_WS_MAX_MESSAGES_PER_WINDOW",
    "DEFAULT_WS_MESSAGE_WINDOW_SECONDS",
    "ENV_MAX_CONCURRENT_CONNECTIONS",
    "ENV_WS_CANCEL_WINDOW_SECONDS",
    "ENV_WS_MAX_CANCELS_PER_WINDOW",
    "ENV_WS_MAX_MESSAGES_PER_WINDOW",
    "ENV_WS_MESSAGE_WINDOW_SECONDS",
]
