"""Admission control and rate limit configuration (constants only)."""

from __future__ import annotations

ENV_MAX_CONCURRENT_CONNECTIONS = "MAX_CONCURRENT_CONNECTIONS"
DEFAULT_MAX_CONCURRENT_CONNECTIONS = 100

ENV_WS_MESSAGE_WINDOW_SECONDS = "WS_MESSAGE_WINDOW_SECONDS"
DEFAULT_WS_MESSAGE_WINDOW_SECONDS = 60.0

# STT streaming is message-heavy. With 80ms chunks, clients send ~750 append messages/minute.
# Default high enough to support 20ms chunking (~3000/min) with headroom.
ENV_WS_MAX_MESSAGES_PER_WINDOW = "WS_MAX_MESSAGES_PER_WINDOW"
DEFAULT_WS_MAX_MESSAGES_PER_WINDOW = 5000

ENV_WS_CANCEL_WINDOW_SECONDS = "WS_CANCEL_WINDOW_SECONDS"
DEFAULT_WS_CANCEL_WINDOW_SECONDS = DEFAULT_WS_MESSAGE_WINDOW_SECONDS

ENV_WS_MAX_CANCELS_PER_WINDOW = "WS_MAX_CANCELS_PER_WINDOW"
DEFAULT_WS_MAX_CANCELS_PER_WINDOW = 50

__all__ = [
    "DEFAULT_MAX_CONCURRENT_CONNECTIONS",
    "DEFAULT_WS_CANCEL_WINDOW_SECONDS",
    "DEFAULT_WS_MAX_CANCELS_PER_WINDOW",
    "DEFAULT_WS_MAX_MESSAGES_PER_WINDOW",
    "DEFAULT_WS_MESSAGE_WINDOW_SECONDS",
    "ENV_MAX_CONCURRENT_CONNECTIONS",
    "ENV_WS_CANCEL_WINDOW_SECONDS",
    "ENV_WS_MAX_CANCELS_PER_WINDOW",
    "ENV_WS_MAX_MESSAGES_PER_WINDOW",
    "ENV_WS_MESSAGE_WINDOW_SECONDS",
]
